stages:
  - build

build:
  image: node:14-alpine
  stage: build
  script:
    - npm ci
    - npm run test
    - npm run build
  artifacts:
    expire_in: 2 weeks
    name: '${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}'
    paths:
      - dist
